# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1051, 614)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("*{\n"
"    border: none;\n"
"    color: #000000;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #000000;\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.slide_menu_container = QtWidgets.QFrame(self.centralwidget)
        self.slide_menu_container.setMinimumSize(QtCore.QSize(0, 0))
        self.slide_menu_container.setMaximumSize(QtCore.QSize(0, 16777215))
        self.slide_menu_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.slide_menu_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.slide_menu_container.setObjectName("slide_menu_container")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.slide_menu_container)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.slide_menu = QtWidgets.QFrame(self.slide_menu_container)
        self.slide_menu.setMinimumSize(QtCore.QSize(198, 0))
        self.slide_menu.setStyleSheet("background-color: #008080;")
        self.slide_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.slide_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.slide_menu.setObjectName("slide_menu")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.slide_menu)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.slide_menu_header = QtWidgets.QFrame(self.slide_menu)
        self.slide_menu_header.setMinimumSize(QtCore.QSize(0, 40))
        self.slide_menu_header.setMaximumSize(QtCore.QSize(16777215, 40))
        self.slide_menu_header.setStyleSheet("background-color: #008080;")
        self.slide_menu_header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.slide_menu_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.slide_menu_header.setObjectName("slide_menu_header")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.slide_menu_header)
        self.horizontalLayout_7.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.slide_menu_header)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.slide_menu_header)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.verticalLayout_4.addWidget(self.slide_menu_header, 0, QtCore.Qt.AlignTop)
        self.slide_menu_body = QtWidgets.QFrame(self.slide_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slide_menu_body.sizePolicy().hasHeightForWidth())
        self.slide_menu_body.setSizePolicy(sizePolicy)
        self.slide_menu_body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.slide_menu_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.slide_menu_body.setObjectName("slide_menu_body")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.slide_menu_body)
        self.verticalLayout_5.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.toolBox = QtWidgets.QToolBox(self.slide_menu_body)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.toolBox.setFont(font)
        self.toolBox.setStyleSheet("QToolBox {\n"
"    background-color: #008080;\n"
"    text-align: left;\n"
"}\n"
"\n"
"QToolBox::tab {\n"
"    border-radius: 5px;\n"
"    background-color: #008080;\n"
"    text-align: left;\n"
"    border: 3px solid #000000;\n"
"}\n"
"\n"
"QToolBox::tab:Hover {\n"
"    border-radius: 10px;\n"
"    background-color: #5F9EA0;\n"
"    text-align: left;\n"
"    border: 3px solid #000000;\n"
"}\n"
"\n"
"")
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 178, 448))
        self.page.setObjectName("page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_5 = QtWidgets.QFrame(self.page)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.frame_5.setFont(font)
        self.frame_5.setStyleSheet("QPushButton {\n"
"    padding: 0 0 0 20px;\n"
"    height: 40px;\n"
"    border-radius: 5px;\n"
"    background-color: #008080;\n"
"    text-align: left;\n"
"    border: 2px solid #000000;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"    padding: 0 0 0 20px;\n"
"    height: 40px;\n"
"    border-radius: 10px;\n"
"    background-color: #000000;\n"
"    color: #008080;\n"
"    text-align: left;\n"
"    border: 2px solid #5F9EA0;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/bluetooth.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_7.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.pushButton_6.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/calendar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon1)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_7.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.pushButton_7.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/cast.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon2)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_7.addWidget(self.pushButton_7)
        self.verticalLayout_6.addWidget(self.frame_5, 0, QtCore.Qt.AlignTop)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/chevron-down.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page, icon3, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 178, 448))
        self.page_2.setObjectName("page_2")
        self.toolBox.addItem(self.page_2, icon3, "")
        self.verticalLayout_5.addWidget(self.toolBox)
        self.verticalLayout_4.addWidget(self.slide_menu_body)
        self.slide_menu_footer = QtWidgets.QFrame(self.slide_menu)
        self.slide_menu_footer.setMinimumSize(QtCore.QSize(0, 40))
        self.slide_menu_footer.setMaximumSize(QtCore.QSize(16777215, 40))
        self.slide_menu_footer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.slide_menu_footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.slide_menu_footer.setObjectName("slide_menu_footer")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.slide_menu_footer)
        self.horizontalLayout_8.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.slide_menu_footer)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_4.addWidget(self.slide_menu_footer, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_2.addWidget(self.slide_menu)
        self.horizontalLayout.addWidget(self.slide_menu_container)
        self.main_body_container = QtWidgets.QFrame(self.centralwidget)
        self.main_body_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_body_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body_container.setObjectName("main_body_container")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_body_container)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.body_header = QtWidgets.QFrame(self.main_body_container)
        self.body_header.setMinimumSize(QtCore.QSize(0, 40))
        self.body_header.setMaximumSize(QtCore.QSize(16777215, 40))
        self.body_header.setStyleSheet("background-color: #008080;")
        self.body_header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.body_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.body_header.setObjectName("body_header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.body_header)
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.body_header)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.open_close_side_bar_btn = QtWidgets.QPushButton(self.frame_2)
        self.open_close_side_bar_btn.setStyleSheet("QPushButton {\n"
"    background-color: #008080; \n"
"    width: 60px;\n"
"    height: 40px; \n"
"    border: 2px solid #000000; \n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"\n"
"QPushButton:Hover {\n"
"    background-color: #5F9EA0; \n"
"    width: 60px;\n"
"    height: 40px; \n"
"    border: 2px solid #000000; \n"
"    border-radius: 10px;\n"
"}")
        self.open_close_side_bar_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/menu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_close_side_bar_btn.setIcon(icon4)
        self.open_close_side_bar_btn.setIconSize(QtCore.QSize(24, 24))
        self.open_close_side_bar_btn.setObjectName("open_close_side_bar_btn")
        self.horizontalLayout_6.addWidget(self.open_close_side_bar_btn, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.frame_2, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.frame = QtWidgets.QFrame(self.body_header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.horizontalLayout_2.addWidget(self.frame, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_3 = QtWidgets.QFrame(self.body_header)
        self.frame_3.setStyleSheet("QPushButton {\n"
"    background-color: #008080; \n"
"    width: 60px;\n"
"    height: 40px; \n"
"    border: 2px solid #000000; \n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"\n"
"QPushButton:Hover {\n"
"    background-color: #5F9EA0; \n"
"    width: 60px;\n"
"    height: 40px; \n"
"    border: 2px solid #000000; \n"
"    border-radius: 10px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.minimize_window_button = QtWidgets.QPushButton(self.frame_3)
        self.minimize_window_button.setStyleSheet("")
        self.minimize_window_button.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/minimize.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimize_window_button.setIcon(icon5)
        self.minimize_window_button.setIconSize(QtCore.QSize(24, 24))
        self.minimize_window_button.setObjectName("minimize_window_button")
        self.horizontalLayout_3.addWidget(self.minimize_window_button)
        self.restore_window_button = QtWidgets.QPushButton(self.frame_3)
        self.restore_window_button.setStyleSheet("")
        self.restore_window_button.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/maximize.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restore_window_button.setIcon(icon6)
        self.restore_window_button.setIconSize(QtCore.QSize(24, 24))
        self.restore_window_button.setObjectName("restore_window_button")
        self.horizontalLayout_3.addWidget(self.restore_window_button)
        self.close_window_button = QtWidgets.QPushButton(self.frame_3)
        self.close_window_button.setStyleSheet("")
        self.close_window_button.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_window_button.setIcon(icon7)
        self.close_window_button.setIconSize(QtCore.QSize(24, 24))
        self.close_window_button.setAutoDefault(False)
        self.close_window_button.setDefault(False)
        self.close_window_button.setFlat(False)
        self.close_window_button.setObjectName("close_window_button")
        self.horizontalLayout_3.addWidget(self.close_window_button)
        self.horizontalLayout_2.addWidget(self.frame_3, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.body_header, 0, QtCore.Qt.AlignTop)
        self.body_main_contents = QtWidgets.QFrame(self.main_body_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.body_main_contents.sizePolicy().hasHeightForWidth())
        self.body_main_contents.setSizePolicy(sizePolicy)
        self.body_main_contents.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.body_main_contents.setFrameShadow(QtWidgets.QFrame.Raised)
        self.body_main_contents.setObjectName("body_main_contents")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.body_main_contents)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.body_contents = QtWidgets.QFrame(self.body_main_contents)
        self.body_contents.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.body_contents.setFrameShadow(QtWidgets.QFrame.Raised)
        self.body_contents.setObjectName("body_contents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.body_contents)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.content_area = QtWidgets.QFrame(self.body_contents)
        self.content_area.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_area.setObjectName("content_area")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.content_area)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.main_body_content_area = QtWidgets.QFrame(self.content_area)
        self.main_body_content_area.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_body_content_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body_content_area.setObjectName("main_body_content_area")
        self.gridLayout = QtWidgets.QGridLayout(self.main_body_content_area)
        self.gridLayout.setObjectName("gridLayout")

        # self.camera_frame = QtWidgets.QFrame(self.main_body_content_area)
        # self.camera_frame.setMinimumSize(QtCore.QSize(640, 480))
        # self.camera_frame.setMaximumSize(QtCore.QSize(640, 480))
        # self.camera_frame.setStyleSheet("background-color: #008080; border-radius: 10px;")
        # self.camera_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        # self.camera_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        # self.camera_frame.setObjectName("camera_frame")
        # self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.camera_frame)
        # self.verticalLayout_16.setContentsMargins(5, 5, 5, 5)
        # self.verticalLayout_16.setSpacing(0)
        # self.verticalLayout_16.setObjectName("verticalLayout_16")
        # self.camera_label = QtWidgets.QLabel(self.camera_frame)
        # self.camera_label.setAutoFillBackground(False)
        # self.camera_label.setText("")
        # self.camera_label.setTextFormat(QtCore.Qt.AutoText)
        # self.camera_label.setPixmap(QtGui.QPixmap("../../Pictures/jetson nano.png"))
        # self.camera_label.setAlignment(QtCore.Qt.AlignCenter)
        # self.camera_label.setObjectName("camera_label")
        # self.verticalLayout_16.addWidget(self.camera_label)
        # self.gridLayout.addWidget(self.camera_frame, 0, 0, 1, 1)

        self.horizontalLayout_10.addWidget(self.main_body_content_area)
        self.main_body_side_menu = QtWidgets.QFrame(self.content_area)
        self.main_body_side_menu.setMaximumSize(QtCore.QSize(60, 16777215))
        self.main_body_side_menu.setStyleSheet("QPushButton {\n"
"    background-color: #008080;\n"
"    border: 2px solid #000000;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:Hover {\n"
"    background-color: #5F9EA0;\n"
"    border: 2px solid #000000;\n"
"    border-radius: 10px;\n"
"}")
        self.main_body_side_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_body_side_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body_side_menu.setObjectName("main_body_side_menu")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.main_body_side_menu)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.right_side_toggle_button_1 = QtWidgets.QPushButton(self.main_body_side_menu)
        self.right_side_toggle_button_1.setMinimumSize(QtCore.QSize(50, 70))
        self.right_side_toggle_button_1.setMaximumSize(QtCore.QSize(50, 70))
        self.right_side_toggle_button_1.setStyleSheet("background-color: #008080; border-top-left-radius: 25px; border-bottom-left-radius: 25px;")
        self.right_side_toggle_button_1.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/toggle-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.right_side_toggle_button_1.setIcon(icon8)
        self.right_side_toggle_button_1.setIconSize(QtCore.QSize(24, 24))
        self.right_side_toggle_button_1.setObjectName("right_side_toggle_button_1")
        self.verticalLayout_10.addWidget(self.right_side_toggle_button_1)
        self.right_side_toggle_button_2 = QtWidgets.QPushButton(self.main_body_side_menu)
        self.right_side_toggle_button_2.setMinimumSize(QtCore.QSize(50, 70))
        self.right_side_toggle_button_2.setMaximumSize(QtCore.QSize(50, 70))
        self.right_side_toggle_button_2.setStyleSheet("background-color: #008080; border-top-left-radius: 25px; border-bottom-left-radius: 25px;")
        self.right_side_toggle_button_2.setText("")
        self.right_side_toggle_button_2.setIcon(icon8)
        self.right_side_toggle_button_2.setIconSize(QtCore.QSize(24, 24))
        self.right_side_toggle_button_2.setObjectName("right_side_toggle_button_2")
        self.verticalLayout_10.addWidget(self.right_side_toggle_button_2)
        self.side_menu_design_frame = QtWidgets.QFrame(self.main_body_side_menu)
        self.side_menu_design_frame.setMinimumSize(QtCore.QSize(50, 0))
        self.side_menu_design_frame.setMaximumSize(QtCore.QSize(50, 16777215))
        self.side_menu_design_frame.setStyleSheet("background-color: #008080; border-top-left-radius: 25px; border-bottom-left-radius: 25px;")
        self.side_menu_design_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.side_menu_design_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.side_menu_design_frame.setObjectName("side_menu_design_frame")
        self.verticalLayout_10.addWidget(self.side_menu_design_frame)
        self.horizontalLayout_10.addWidget(self.main_body_side_menu)
        self.verticalLayout_3.addWidget(self.content_area)
        self.body_footer = QtWidgets.QFrame(self.body_contents)
        self.body_footer.setMinimumSize(QtCore.QSize(0, 40))
        self.body_footer.setMaximumSize(QtCore.QSize(16777215, 40))
        self.body_footer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.body_footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.body_footer.setObjectName("body_footer")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.body_footer)
        self.horizontalLayout_9.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label = QtWidgets.QLabel(self.body_footer)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #008080;")
        self.label.setObjectName("label")
        self.horizontalLayout_9.addWidget(self.label)
        self.verticalLayout_3.addWidget(self.body_footer)
        self.horizontalLayout_4.addWidget(self.body_contents)
        self.status_side_menu = QtWidgets.QFrame(self.body_main_contents)
        self.status_side_menu.setMinimumSize(QtCore.QSize(0, 0))
        self.status_side_menu.setMaximumSize(QtCore.QSize(0, 16777215))
        self.status_side_menu.setStyleSheet("background-color: #008080;")
        self.status_side_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.status_side_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.status_side_menu.setObjectName("status_side_menu")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.status_side_menu)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.status_menu_body = QtWidgets.QFrame(self.status_side_menu)
        self.status_menu_body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.status_menu_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.status_menu_body.setObjectName("status_menu_body")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.status_menu_body)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.toolBox_2 = QtWidgets.QToolBox(self.status_menu_body)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.toolBox_2.setFont(font)
        self.toolBox_2.setStyleSheet("QToolBox {\n"
"    background-color: #008080;\n"
"    text-align: left;\n"
"}\n"
"\n"
"QToolBox::tab {\n"
"    border-radius: 5px;\n"
"    background-color: #008080;\n"
"    text-align: left;\n"
"    border: 3px solid #000000;\n"
"}\n"
"\n"
"QToolBox::tab:Hover {\n"
"    border-radius: 10px;\n"
"    background-color: #5F9EA0;\n"
"    text-align: left;\n"
"    border: 3px solid #000000;\n"
"}\n"
"\n"
"")
        self.toolBox_2.setObjectName("toolBox_2")
        self.status_panel = QtWidgets.QWidget()
        self.status_panel.setGeometry(QtCore.QRect(0, 0, 282, 492))
        self.status_panel.setStyleSheet("")
        self.status_panel.setObjectName("status_panel")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.status_panel)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.side_menu_status_panel_frame = QtWidgets.QFrame(self.status_panel)
        self.side_menu_status_panel_frame.setStyleSheet("background-color: black; border-radius: 10px;")
        self.side_menu_status_panel_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.side_menu_status_panel_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.side_menu_status_panel_frame.setObjectName("side_menu_status_panel_frame")
        self.verticalLayout_15.addWidget(self.side_menu_status_panel_frame)
        self.toolBox_2.addItem(self.status_panel, "")
        self.cameras_panel = QtWidgets.QWidget()
        self.cameras_panel.setGeometry(QtCore.QRect(0, 0, 282, 492))
        self.cameras_panel.setObjectName("cameras_panel")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.cameras_panel)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.side_menu_camera_panel_frame = QtWidgets.QFrame(self.cameras_panel)
        self.side_menu_camera_panel_frame.setStyleSheet("background-color: black; border-radius: 10px;")
        self.side_menu_camera_panel_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.side_menu_camera_panel_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.side_menu_camera_panel_frame.setObjectName("side_menu_camera_panel_frame")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.side_menu_camera_panel_frame)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.scrollArea = QtWidgets.QScrollArea(self.side_menu_camera_panel_frame)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 282, 492))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_13.setContentsMargins(5, 10, 5, 10)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")


        # self.side_camera_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        # self.side_camera_frame.setMinimumSize(QtCore.QSize(260, 150))
        # self.side_camera_frame.setMaximumSize(QtCore.QSize(260, 150))
        # self.side_camera_frame.setStyleSheet("background-color: #008080; border-radius: 10px;")
        # self.side_camera_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        # self.side_camera_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        # self.side_camera_frame.setObjectName("side_camera_frame")
        # self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.side_camera_frame)
        # self.verticalLayout_14.setContentsMargins(5, 5, 5, 5)
        # self.verticalLayout_14.setSpacing(5)
        # self.verticalLayout_14.setObjectName("verticalLayout_14")
        # self.side_camera_label = QtWidgets.QLabel(self.side_camera_frame)
        # self.side_camera_label.setStyleSheet("border-radius: 10px;")
        # self.side_camera_label.setText("")
        # self.side_camera_label.setPixmap(QtGui.QPixmap("../../Pictures/laptop.jpg"))
        # self.side_camera_label.setObjectName("side_camera_label")
        # self.verticalLayout_14.addWidget(self.side_camera_label)
        # self.verticalLayout_13.addWidget(self.side_camera_frame, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)


        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_12.addWidget(self.scrollArea)
        self.verticalLayout_11.addWidget(self.side_menu_camera_panel_frame)
        self.toolBox_2.addItem(self.cameras_panel, "")
        self.verticalLayout_9.addWidget(self.toolBox_2)
        self.verticalLayout_8.addWidget(self.status_menu_body)
        self.horizontalLayout_4.addWidget(self.status_side_menu)
        self.verticalLayout.addWidget(self.body_main_contents)
        self.horizontalLayout.addWidget(self.main_body_container)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        self.toolBox_2.setCurrentIndex(1)
        self.toolBox_2.layout().setSpacing(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "SIR Systems"))
        self.label_4.setText(_translate("MainWindow", "Logo"))
        self.pushButton_5.setText(_translate("MainWindow", "Item 1"))
        self.pushButton_6.setText(_translate("MainWindow", "Item 2"))
        self.pushButton_7.setText(_translate("MainWindow", "Item 3"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Dropdown Menu 1"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Dropdown 2"))
        self.label_5.setText(_translate("MainWindow", "Powered By SIR"))
        self.label_2.setText(_translate("MainWindow", "Jetson Nano"))
        self.label.setText(_translate("MainWindow", "Intrusion Detection System"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.status_panel), _translate("MainWindow", "Status Panel"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.cameras_panel), _translate("MainWindow", "Cameras Panel"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
